# [Info]
# 左上角标题
site_name: anuouan-weblog
site_url: https://anuouan.github.io
site_author: anuouan
site_description: anuouan-weblog

# [导航栏]
nav:
  - 主页:
      - index.md
      - 博客分类: 博客分类/index.md
      - 报错日志: 错误日志/index.md
      - 网站部署: 网站部署/index.md
      - 生活分享: life-sharing/index.md
      - 关于我: 关于我/index.md
  - 博客分类:
      - 博客分类/index.md
      - JavaWeb: 博客分类/javaweb/index.md
      - Maven:
          - 博客分类/maven/index.md
          - 1.maven自学笔记: 博客分类/maven/1.maven自学教程.md
      - Git:
          - 博客分类/git/index.md
          - 1.git自学笔记: 博客分类/git/1.git自学教程.md
          - 2.Git常用命令: 博客分类/git/2.Git常用命令.md
      - MyBatis:
          - 博客分类/mybatis/index.md
          - 1.MyBatis自学笔记: 博客分类/mybatis/1.MyBatis自学笔记.md
      - Spring:
          - 博客分类/spring/index.md
          - 1.Spring自学笔记: 博客分类/spring/1.Spring自学笔记.md
      - SpringMVC:
          - 博客分类/spring-mvc/index.md
          - 1.SpringMVC自学笔记: 博客分类/spring-mvc/1.SpringMVC自学笔记.md
      - Linux:
          - 博客分类/linux/index.md
          - 1.Linux vi/vim: 博客分类/linux/1.VIM.md
          - 2.Linux命令查询.md: 博客分类/linux/2.Linux命令查询.md
      - Redis:
          - 博客分类/redis/index.md
          - 1.Redis笔记: 博客分类/redis/1.Redis笔记.md
      - 设计模式:
          - 博客分类/设计模式/index.md
          - 1.设计模式: 博客分类/设计模式/index.md
      - 算法笔记:
          - 博客分类/算法日志/index.md
          - 数组:
              - 1.704 二分查找: 博客分类/算法日志/数组/1.704 二分查找.md
              - 2.27 移除元素: 博客分类/算法日志/数组/2.27 移除元素.md
              - 3.977 有序数组的平方: 博客分类/算法日志/数组/3.977 有序数组的平方.md
              - 4.209 长度最小的子数组: 博客分类/算法日志/数组/4.209 长度最小的子数组.md
              - 5.59 螺旋矩阵 II: 博客分类/算法日志/数组/5.59 螺旋矩阵 II.md
          - 链表:
              - 1.203 移除链表元素: 博客分类/算法日志/链表/1.203 移除链表元素.md
              - 2.707 设计链表: 博客分类/算法日志/链表/2.707 设计链表.md
              - 3.206 反转链表: 博客分类/算法日志/链表/3.206 反转链表.md
              - 4.24 两两交换链表中的节点: 博客分类/算法日志/链表/4.24 两两交换链表中的节点.md
              - 5.19 删除链表的倒数第 N 个结点: 博客分类/算法日志/链表/5.19 删除链表的倒数第 N 个结点.md
      - 软件安装配置:
          - 博客分类/software-install-config/index.md
          - 1.mysql-8.x免安装配置: 博客分类/software-install-config/1.mysql-8.x免安装配置.md
          - 2.Navicat16激活破解: 博客分类/software-install-config/2.Navicat16激活破解.md
          - 3.Offic下载与破解: 博客分类/software-install-config/3.Offic下载与破解.md
          - 4.eclipse基础配置及快捷键: 博客分类/software-install-config/4.eclipse基础配置及快捷键.md
  - 错误日志:
      - 错误日志/index.md
      - Git错误日志:
          - 错误日志/Git错误日志/index.md
          - 1.Git使用SSH连接GitHub报错: 错误日志/Git错误日志/1.Git使用SSH连接GitHub报错.md
      - MkDocs错误日志:
          - 错误日志/MkDocs错误日志/index.md
          - 1.mkdocs图片路径找不到问题: 错误日志/MkDocs错误日志/1.mkdocs图片路径找不到问题.md
          - 2.mkdocs不支持无序嵌套问题: 错误日志/MkDocs错误日志/2.mkdocs不支持无序嵌套问题.md
      - Linux错误日志:
          - 错误日志/Linux错误日志/index.md
          - 1.在虚拟机安装Ubuntu时出现窗口不全: 错误日志/Linux错误日志/1.在虚拟机安装Ubuntu时出现窗口不全.md
  - 网站部署:
      - 网站部署/index.md
      - 1.个人网站搭建: 网站部署/1.网站部署.md
      - 2.Clash 永久修改配置跳过 ChatGPT 封禁: 网站部署/2.Clash 永久修改配置跳过 ChatGPT 封禁 IP.md
  - 生活分享:
      - 生活分享/index.md
      - 1.出门必备物品清单: 生活分享/1.出门必备物品清单.md
      - 2.实习必问的问题: 生活分享/2.实习必问的问题.md
  - 书籍分享:
      - 书籍分享/index.md
  - 关于我:
      - 关于我/index.md
      - 关于我/QQ留言.md
      - 关于我/打赏支持.md
      - 关于我/找工作.md

# [UI]
# [top]
theme:

  name: material
  favicon: mkdocs/images/favicon.png  # 更改网站的 favicon
  logo: mkdocs/images/favicon.png     # 更改网站的 logo
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: white
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: green
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/anuouan
repo_name: anuouan's github
# [bottom-left corner]
# [版权说明]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: Copyright © 2024 Anuouan | Do not share my personal information
# [bottom-right corner]
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | anuouan
      icon: fontawesome/brands/github
      link: https://github.com/anuouan
    - name: Bilibili | anuouan
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1599014047
    - name: anuouan QQ 512864110
      icon: fontawesome/brands/qq
      link: https://anuouan.github.io/关于我/QQ%E7%95%99%E8%A8%80.html
    - name: 小红书 | anuouan
      icon: fontawesome/solid/images
      link: https://www.xiaohongshu.com/user/profile/62655b530000000010007573
    - name: 打赏支持
      icon: fontawesome/solid/mug-saucer
      link: https://anuouan.github.io/关于我/打赏支持.html

# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
markdown_extensions:
  - mdx_truly_sane_lists
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      anchor_linenums: true
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css
use_directory_urls: false
