# 工作流程的名称
name: Publish docs via GitHub Pages

# 触发此工作流程的事件，当向'main'分支推送代码时，会触发此工作流程
on:
  push:
    branches:
      - main

# 定义工作流程中的任务
jobs:
  build:
    # 任务的名称
    name: Deploy docs

    # 在哪个环境上运行此任务，这里选择的是Ubuntu的最新版本
    runs-on: ubuntu-latest

    # 任务的执行步骤
    steps:
      # 步骤1：检出main分支的代码
      - name: Checkout main
        # 使用actions/checkout的v2版本，用于检出代码
        uses: actions/checkout@v2

      # 步骤2：部署文档
      - name: Deploy docs
        # 使用mhausenblas/mkdocs-deploy-gh-pages的master版本，这是一个用于部署MkDocs生成的文档的GitHub Action
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        with:
          # 设置MkDocs的额外插件
          extra_plugins:
            - pip install mdx-truly-sane-lists  # 插件1的名称
#            - plugin2  # 插件2的名称
            # ... 添加更多插件
        # 设置环境变量
        env:
          # 使用GitHub提供的秘密令牌，用于授权访问仓库等操作
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # 额外的包，可能是为了构建文档所需的依赖
          EXTRA_PACKAGES: build-base