# 工作流程的名称  
name: Publish docs via GitHub Pages

# 触发此工作流程的事件  
on:
  # 当代码推送到'main'分支时触发  
  push:
    branches:
      - main

# 定义工作流程中要执行的任务（job）  
jobs:
  # 任务的名称为'build'  
  build:
    # 任务的展示名称为'Deploy docs'  
    name: Deploy docs
    # 任务在Ubuntu最新的环境中运行  
    runs-on: ubuntu-latest
    # 任务执行的步骤列表  
    steps:
      # 第一步的名称是'Checkout main'  
      - name: Checkout main
        # 使用actions/checkout@v2这个Action来检出代码  
        # 这确保了工作流程能够访问到最新的代码  
        uses: actions/checkout@v2

      # 第二步的名称是'Deploy docs'  
      - name: Deploy docs
        # 使用mhausenblas/mkdocs-deploy-gh-pages@master这个Action来部署MKDocs生成的文档到GitHub Pages  
        # 这个Action封装了MKDocs的构建和部署过程  
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # 设置环境变量，这些环境变量将在Action的执行过程中被使用  
        env:
          # 使用GitHub提供的加密令牌，用于授权部署操作  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 指定MKDocs的配置文件，默认为'mkdocs.yml'  
          CONFIG_FILE: mkdocs.yml
          # 额外的包，这里指定了'build-base'，这通常包含了一些编译工具，用于解决依赖问题  
          EXTRA_PACKAGES: build-base